// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package x.shiny.example.proto;

public interface EchoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:x.shiny.example.proto.EchoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
