// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package x.shiny.example.proto;

public final class Echo {
  private Echo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x_shiny_example_proto_EchoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x_shiny_example_proto_EchoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_x_shiny_example_proto_EchoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_x_shiny_example_proto_EchoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\necho.proto\022\025x.shiny.example.proto\"\033\n\013E" +
      "choRequest\022\014\n\004name\030\001 \001(\t\"\034\n\014EchoResponse" +
      "\022\014\n\004name\030\001 \001(\t2^\n\013EchoService\022O\n\004echo\022\"." +
      "x.shiny.example.proto.EchoRequest\032#.x.sh" +
      "iny.example.proto.EchoResponseB\"\n\025x.shin" +
      "y.example.protoB\004EchoP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_x_shiny_example_proto_EchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_x_shiny_example_proto_EchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x_shiny_example_proto_EchoRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_x_shiny_example_proto_EchoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_x_shiny_example_proto_EchoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_x_shiny_example_proto_EchoResponse_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
