// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package x.shiny.example.proto;

/**
 * Protobuf service {@code x.shiny.example.proto.EchoService}
 */
public  abstract class EchoService
    implements com.google.protobuf.Service {
  protected EchoService() {}

  public interface Interface {
    /**
     * <code>rpc Echo(.x.shiny.example.proto.EchoRequest) returns (.x.shiny.example.proto.EchoResponse);</code>
     */
    public abstract void echo(
        com.google.protobuf.RpcController controller,
        x.shiny.example.proto.EchoRequest request,
        com.google.protobuf.RpcCallback<x.shiny.example.proto.EchoResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new EchoService() {
      @java.lang.Override
      public  void echo(
          com.google.protobuf.RpcController controller,
          x.shiny.example.proto.EchoRequest request,
          com.google.protobuf.RpcCallback<x.shiny.example.proto.EchoResponse> done) {
        impl.echo(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.echo(controller, (x.shiny.example.proto.EchoRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return x.shiny.example.proto.EchoRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return x.shiny.example.proto.EchoResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc Echo(.x.shiny.example.proto.EchoRequest) returns (.x.shiny.example.proto.EchoResponse);</code>
   */
  public abstract void echo(
      com.google.protobuf.RpcController controller,
      x.shiny.example.proto.EchoRequest request,
      com.google.protobuf.RpcCallback<x.shiny.example.proto.EchoResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return x.shiny.example.proto.Echo.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.echo(controller, (x.shiny.example.proto.EchoRequest)request,
          com.google.protobuf.RpcUtil.<x.shiny.example.proto.EchoResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return x.shiny.example.proto.EchoRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return x.shiny.example.proto.EchoResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends x.shiny.example.proto.EchoService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void echo(
        com.google.protobuf.RpcController controller,
        x.shiny.example.proto.EchoRequest request,
        com.google.protobuf.RpcCallback<x.shiny.example.proto.EchoResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        x.shiny.example.proto.EchoResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          x.shiny.example.proto.EchoResponse.class,
          x.shiny.example.proto.EchoResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public x.shiny.example.proto.EchoResponse echo(
        com.google.protobuf.RpcController controller,
        x.shiny.example.proto.EchoRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public x.shiny.example.proto.EchoResponse echo(
        com.google.protobuf.RpcController controller,
        x.shiny.example.proto.EchoRequest request)
        throws com.google.protobuf.ServiceException {
      return (x.shiny.example.proto.EchoResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        x.shiny.example.proto.EchoResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:x.shiny.example.proto.EchoService)
}

